expressions:
  gen:
    name: Gender Factor
    abbr: gen
    type: Numerical
    min: -600
    max: 600
    default_value: 0
    is_flag: true
    flag: g
  hbre:
    name: Breathiness (HiFiSampler)
    abbr: mbre
    type: Numerical
    min: 0
    max: 500
    default_value: 100
    is_flag: true
    flag: Hb
  hhrm:
    name: Voice/Harmonic (HiFiSampler)
    abbr: hhrm
    type: Numerical
    min: 0
    max: 150
    default_value: 100
    is_flag: true
    flag: Hv
  hgwl:
    name: Growl (HiFiSampler)
    abbr: hgwl
    type: Numerical
    min: 0
    max: 100
    default_value: 0
    is_flag: true
    flag: HG
  norm:
    name: Normalizalize
    abbr: norm
    type: Numerical
    min: 0
    max: 100
    default_value: 100
    is_flag: true
    flag: P
  hten:
    name: Tension (HiFiSampler)
    abbr: hten
    type: Numerical
    min: -100
    max: 100
    defaule_value: 0
    is_flag: true
    flag: Ht
